# Generated by Django 5.2 on 2025-05-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0003_race_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='city',
            field=models.CharField(max_length=100, verbose_name='도시'),
        ),
    ]
