# Generated by Django 5.2 on 2025-05-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '코스종류',
                'verbose_name_plural': '코스종류',
                'db_table': 'course_type',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='대회제목')),
                ('date', models.DateField(verbose_name='대회날짜')),
                ('region', models.CharField(max_length=100, verbose_name='지역')),
                ('regi_status', models.CharField(choices=[('open', '접수중'), ('closed', '접수완료'), ('wait', '접수예정')], max_length=10, verbose_name='접수상태')),
                ('race_image', models.ImageField(blank=True, null=True, upload_to='race_images/', verbose_name='대회이미지')),
                ('homepage_url', models.URLField(verbose_name='홈페이지url')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_type', models.ManyToManyField(related_name='races', to='race.coursetype', verbose_name='코스종류')),
            ],
            options={
                'verbose_name': '대회',
                'verbose_name_plural': '대회',
                'db_table': 'race',
            },
        ),
    ]
