# Generated by Django 5.2 on 2025-05-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0002_alter_coursetype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='city',
            field=models.CharField(default='수도권', max_length=100, verbose_name='도시'),
        ),
    ]
