# Generated by Django 5.2 on 2025-05-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_customuser_options_alter_customuser_table'),
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='race',
            field=models.ManyToManyField(blank=True, related_name='race_bookmark', to='race.race', verbose_name='저장한대회'),
        ),
    ]
